server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sids-db
    username: sa
    password: Mp10fi#!
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
