INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (1, '2022-04-23', null, 'A+');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (2, '2022-04-23', null, 'A-');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (3, '2022-04-23', null, 'B+');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (4, '2022-04-23', null, 'B-');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (5, '2022-04-23', null, 'AB+');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (6, '2022-04-23', null, 'AB-');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (7, '2022-04-23', null, 'O+');
INSERT ignore INTO `sids-db`.tipo_sanguineo (id, data_criacao, data_modificacao, nome) VALUES (8, '2022-04-23', null, 'O-');

INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (1, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (2, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (7, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (2, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (3, 3);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (7, 3);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 3);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 4);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (1, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (2, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (3, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (5, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (6, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (7, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (2, 6);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (6, 6);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 6);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (7, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_recebedores (tipo_sanguineo_id, tipo_sanguineo_recebedor_id) VALUES (8, 8);


INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (1, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 1);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (1, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (2, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (6, 2);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (3, 3);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 3);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (3, 4);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (4, 4);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 4);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (6, 4);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 5);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 6);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (6, 6);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (1, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (3, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (7, 7);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (1, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (2, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (3, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (4, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (5, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (6, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (7, 8);
INSERT ignore INTO `sids-db`.tipo_sanguineo_tipos_sanguineos_doadores (tipo_sanguineo_id, tipo_sanguineo_doador_id) VALUES (8, 8);
